# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6290059af6feaeac170a3a4a7108ce0e"
name = "enzy-delivery-app"
application_url = "https://bestsellers-alloy-years-symposium.trycloudflare.com"
embedded = true
handle = "enzy-delivery-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_shipping,write_shipping"

[auth]
redirect_urls = ["https://bestsellers-alloy-years-symposium.trycloudflare.com/auth/callback", "https://bestsellers-alloy-years-symposium.trycloudflare.com/auth/shopify/callback", "https://bestsellers-alloy-years-symposium.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
